name: muslim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  flutter_launcher_icons: ^0.11.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_qiblah: 2.0.2
  flutter_svg: 1.1.1+1
  hijri: ^3.0.0
  intl: 0.17.0
  geolocator: 7.6.0
  geocoding: 2.0.4
  adhan: ^2.0.0-nullsafety.2
  flutter_local_notifications: ^11.0.0
  flutter_native_timezone: ^2.0.0
  get_storage: 2.0.3
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  cached_network_image: 3.2.3
  share_plus: 6.3.0
  app_settings: ^4.1.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/icon/
    - assets/images/
    - assets/json/
    - assets/fonts/
  fonts: 
    - family: UthmanicHafs
      fonts: 
        - asset: assets/fonts/Uthmanic_Script_HAFS_Regular.otf
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/praying.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/praying.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/praying.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/praying.png"
