name: muslim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  audioplayers: 0.20.1
  persistent_bottom_nav_bar: ^4.0.2
  permission_handler: ^10.2.0
  flutter_qiblah: 2.0.2
  flutter_svg: 1.1.1+1
  hijri: ^3.0.0
  intl: 0.17.0
  geolocator: 7.6.0
  geocoding: 2.0.4
  quran: 1.1.2
  adhan: ^2.0.0-nullsafety.2
  flutter_local_notifications: ^11.0.0
  flutter_native_timezone: ^2.0.0
  get_storage: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/icon/
    - assets/images/
    - assets/json/
    - assets/fonts/
  uses-material-design: true

