// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1Is8q2kp2Q8o7U3O5TzQFjYc7PVVE6s',
    appId: '1:671915168478:web:e073acca56b8d73c21684f',
    messagingSenderId: '671915168478',
    projectId: 'muslimapp-da8fc',
    authDomain: 'muslimapp-da8fc.firebaseapp.com',
    storageBucket: 'muslimapp-da8fc.appspot.com',
    measurementId: 'G-S10VENVQK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MpO0I_4SZipR1nMsu3yyPWkzn2-4GaA',
    appId: '1:671915168478:android:fb8f5d981ca813f421684f',
    messagingSenderId: '671915168478',
    projectId: 'muslimapp-da8fc',
    storageBucket: 'muslimapp-da8fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbeGMMsFPbN7GbYDLcXtB8iQlwkINTHI',
    appId: '1:671915168478:ios:ab7f6e0ab31389f621684f',
    messagingSenderId: '671915168478',
    projectId: 'muslimapp-da8fc',
    storageBucket: 'muslimapp-da8fc.appspot.com',
    iosClientId: '671915168478-m3t16h9l69a3gvflu264h6d6ijitr7ju.apps.googleusercontent.com',
    iosBundleId: 'com.zeekands.muslimApp',
  );
}
